name: Testnet [Deploy]
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  testnet-build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: v16.19.1
          registry-url: https://npm.pkg.github.com
      - name: Setup Git
        run: |
          git config --global user.name "xLabs Playground CI"
          git config --global user.email "devops@xlabs-playground.xyz"
      - name: Install dependencies
        run: npm ci
      - name: Compute Version
        run: |
          npm version prerelease --preid T$(echo ${{ github.sha }} | cut -c -10)
          echo "_PKG_VERSION=$(node -p -e "require('./package.json').version")" >> "${GITHUB_ENV}"
          echo "_BRANCH_NAME_SHA=$(echo ${{ github.event.pull_request.head.ref }} | sha256sum | cut -c -10)" >> "${GITHUB_ENV}"
      - name: Build and Publish
        env:
          PUBLIC_URL: ${{ env._PKG_VERSION }}
          REACT_APP_CLUSTER: testnet
        run: |
          echo 'REACT_APP_VERSION=$npm_package_version' > .env
          npm run build
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          npm run set-version
          npm publish
      - name: Checkout testnet branch
        uses: actions/checkout@v3
        with:
          ref: testnet
          path: testnet
      - name: Trigger a testnet Deploy 
        run: |
          mkdir -p testnet/${_BRANCH_NAME_SHA}
          pushd testnet/${_BRANCH_NAME_SHA}
          [[ ! -f .latest ]] && touch .latest
          [[ ! -f .artifacts ]] && touch .artifacts
          cat .latest >> .artifacts
          echo ${_PKG_VERSION} > .latest
          git add .artifacts .latest
          git commit -m"Update testnet artifacts"
          git push
